# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonAPI

  target 'PokemonAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonAPIUITests' do
    # Pods for testing
  end

  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireImage', '~> 4.1'


end
